name: Build and Test CDR Generator module
on:
  push:
    branches:
      - '**'
    paths:
      - 'cdr_generator/src/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'cdr_generator/src/**'

jobs:
  test-cdr:
    runs-on: ubuntu-latest
    name: Run CDR Generator Module Tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run CDR Generator Tests
        run: |
          cd cdr_generator
          mvn test
