name: Build and Test modules
on:
  push:
    branches:
      - '**'

jobs:
  test-cdr:
    runs-on: ubuntu-latest
    name: Run CDR Generator Module Tests
    if: contains(github.event.commits.*.modified, 'cdr_generator/') || contains(github.event.commits.*.added, 'cdr_generator/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run CDR Generator Tests
        run: |
          cd cdr_generator
          mvn test

  test-brt:
    runs-on: ubuntu-latest
    name: Run BRT Service Module Tests
    if: contains(github.event.commits.*.modified, 'brt/') || contains(github.event.commits.*.added, 'brt/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run BRT Tests
        run: |
          cd brt
          mvn test

  test-hrs:
    runs-on: ubuntu-latest
    name: Run HRS Service Module Tests
    if: contains(github.event.commits.*.modified, 'hrs/') || contains(github.event.commits.*.added, 'hrs/')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run HRS Tests
        run: |
          cd hrs
          mvn test
